import type { Metadata } from "next";
import { Geist, Geist_Mono , Inter } from "next/font/google";
import "./globals.css";
import ConfirmationPopup from "@/components/ConfirmationPopup";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter = Inter({
  display:"swap",
  variable:"--font-inter",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${geistSans.variable} ${geistMono.variable} font-inter scrollbar-hidden antialiased w-full bg-primary-bg flex h-full overflow-y-scroll flex-row  `}
      > 
        <div className="flex flex-col gap-5 w-full h-full  bg-primary-bg">
          {children}
          <ConfirmationPopup/>
        </div>
      </body>
    </html>
  );
}
